from hero import Hero

hero1 = Hero("Itigo",100, 25, 100,"Sword")
hero2 = Hero("Aisen",300, 50, 10,"Hands")
hero3 = Hero("Bakuia",100,55,50,"Flower")

hero1.print_info()
hero2.print_info()
hero3.print_info()

print("\n Itigo:I will stop and kill you")
print("\n Aisen:Are you can?")
print("\n Itigo:yes i can ")
hero1.strike(hero2)
print("\n Itigo:see i can hurt you")
print("\n Aisen:no pain at all")
print("\n Itigo:how about that")
hero1.strike(hero2)
hero1.strike(hero2)
print("\n Aisen:ok you got me")
hero2.strike(hero1)
print("\n Itigo:damn you so strong")
hero2.strike(hero1)
print("\n Aisen:You can win me")
print("\n Aisen:Just surrender and die")
hero2.strike(hero1)
print("\n Itigo:I low hp")
print("\n Itigo:I need use boost")
print("\n Itigo:Bankai\n")
hero1.strike(hero2)
hero1.strike(hero2)
hero1.strike(hero2)
hero1.strike(hero2)
hero1.strike(hero2)
print("\n Aisen:I underestimated you")
print("\n Aisen:ok lets finish this fight ")
hero1.strike(hero3)
print("\n Aisen:what are doing here Bakuia")
print("\n Bakuia:kill you ")
hero3.strike(hero2)
print("\n Bakuia:Good bye ")
hero3.fight(hero2)
print("\n Itigo:Thanks for help Bakuia")
print("GG")